spring.application.name=tarea4

# Usar H2 como base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Crear y actualizar automáticamente las tablas
spring.jpa.hibernate.ddl-auto=update

# Mostrar las queries en consola (opcional)
spring.jpa.show-sql=true

# Habilitar consola web de H2 (útil para testear)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Quitar el whiteLabel Error
server.error.whitelabel.enabled=false

